apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-usjcxutz
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/go-usjcxutz:azure-561609edf06c678333bab1e8cd740c2c8c4b8565
          name: container-image
